baseurl = "https://robbfitzsimmons.com"
title = "Robb Fitzsimmons"
copyright = "&copy; 2016 Robb Fitzsimmons"
languageCode = "en-us"
theme = "academic"
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-34179169-1"


[params]
#  name = ""
#  role = ""
#  organization = ""
  avatar = "portrait.png"
  email = "robbfitzsimmons@gmail.com"
  address = "1683 Cambridge Street, Suite 1, Cambridge MA 02138"
  phone = "+1 630 890 9451"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "robbfitzsimmons"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["robb.css"]
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:robb@linnaean.co"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/robbfitzsimmons"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/robbfitzsimmons"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/robbfitzsimmons"



# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#bio"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5
